//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly
    {
        public assembly()
        {
            this.partassembly = new HashSet<partassembly>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
    
        public virtual ICollection<partassembly> partassembly { get; set; }
    }
}
