//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class basepart
    {
        public basepart()
        {
            this.partassembly = new HashSet<partassembly>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int manufacturerid { get; set; }
        public int parttypeid { get; set; }
        public string image { get; set; }
        public decimal price { get; set; }
    
        public virtual manufacturer manufacturer { get; set; }
        public virtual parttype parttype { get; set; }
        public virtual @case @case { get; set; }
        public virtual cpu cpu { get; set; }
        public virtual gpu gpu { get; set; }
        public virtual motherboard motherboard { get; set; }
        public virtual ICollection<partassembly> partassembly { get; set; }
        public virtual powersupply powersupply { get; set; }
        public virtual processorcooler processorcooler { get; set; }
        public virtual ram ram { get; set; }
        public virtual storagedevice storagedevice { get; set; }
    }
}
