//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GMO1CEntities : DbContext
    {
        public GMO1CEntities()
            : base("name=GMO1CEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<assembly> assembly { get; set; }
        public DbSet<basepart> basepart { get; set; }
        public DbSet<boardformfactorcase> boardformfactorcase { get; set; }
        public DbSet<@case> @case { get; set; }
        public DbSet<casesize> casesize { get; set; }
        public DbSet<certificate> certificate { get; set; }
        public DbSet<cpu> cpu { get; set; }
        public DbSet<fandimension> fandimension { get; set; }
        public DbSet<formfactor> formfactor { get; set; }
        public DbSet<gpu> gpu { get; set; }
        public DbSet<gpuinterface> gpuinterface { get; set; }
        public DbSet<hdd> hdd { get; set; }
        public DbSet<igpu> igpu { get; set; }
        public DbSet<manufacturer> manufacturer { get; set; }
        public DbSet<memorytype> memorytype { get; set; }
        public DbSet<motherboard> motherboard { get; set; }
        public DbSet<partassembly> partassembly { get; set; }
        public DbSet<parttype> parttype { get; set; }
        public DbSet<powersupply> powersupply { get; set; }
        public DbSet<processorcooler> processorcooler { get; set; }
        public DbSet<ram> ram { get; set; }
        public DbSet<socket> socket { get; set; }
        public DbSet<socketprocessorcooler> socketprocessorcooler { get; set; }
        public DbSet<ssd> ssd { get; set; }
        public DbSet<storagedevice> storagedevice { get; set; }
        public DbSet<storagedeviceinterface> storagedeviceinterface { get; set; }
        public DbSet<storagedevicetype> storagedevicetype { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<videoconnector> videoconnector { get; set; }
        public DbSet<videoconnectorgpu> videoconnectorgpu { get; set; }
    }
}
