//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class @case
    {
        public @case()
        {
            this.boardformfactorcase = new HashSet<boardformfactorcase>();
        }
    
        public int id { get; set; }
        public int sizeid { get; set; }
        public int expansionslots { get; set; }
        public int fans { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual ICollection<boardformfactorcase> boardformfactorcase { get; set; }
        public virtual casesize casesize { get; set; }
    }
}
