//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class casesize
    {
        public casesize()
        {
            this.@case = new HashSet<@case>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<@case> @case { get; set; }
    }
}
