//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public certificate()
        {
            this.powersupply = new HashSet<powersupply>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<powersupply> powersupply { get; set; }
    }
}
