//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class formfactor
    {
        public formfactor()
        {
            this.boardformfactorcase = new HashSet<boardformfactorcase>();
            this.motherboard = new HashSet<motherboard>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<boardformfactorcase> boardformfactorcase { get; set; }
        public virtual ICollection<motherboard> motherboard { get; set; }
    }
}
