//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class igpu
    {
        public igpu()
        {
            this.cpu = new HashSet<cpu>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<cpu> cpu { get; set; }
    }
}
