//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class processorcooler
    {
        public processorcooler()
        {
            this.socketprocessorcooler = new HashSet<socketprocessorcooler>();
        }
    
        public int id { get; set; }
        public int fandimensionid { get; set; }
        public int heatpipes { get; set; }
        public int minspeed { get; set; }
        public int maxspeed { get; set; }
        public double noiselevel { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual fandimension fandimension { get; set; }
        public virtual ICollection<socketprocessorcooler> socketprocessorcooler { get; set; }
    }
}
