//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class socket
    {
        public socket()
        {
            this.cpu = new HashSet<cpu>();
            this.motherboard = new HashSet<motherboard>();
            this.socketprocessorcooler = new HashSet<socketprocessorcooler>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<cpu> cpu { get; set; }
        public virtual ICollection<motherboard> motherboard { get; set; }
        public virtual ICollection<socketprocessorcooler> socketprocessorcooler { get; set; }
    }
}
