//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr15
{
    using System;
    using System.Collections.Generic;
    
    public partial class videoconnectorgpu
    {
        public int id { get; set; }
        public int gpuid { get; set; }
        public int videoconnectorid { get; set; }
    
        public virtual gpu gpu { get; set; }
        public virtual videoconnector videoconnector { get; set; }
    }
}
